services:
  web:
    build: .
    command: gunicorn django_project.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - 'DJANGO_SECRET_KEY=5BnmvOQ1BWcK_aEC9VSfGDEY9QAH-Yuzr-dLFL4TCRsq48VuHiI'

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

volumes:
  postgres_data:
